### ISSUE TITLE
run "python demo.py" issue

### ISSUE THREAD

**Issue by Jaypancool** [tmadl/pySeqSLAM#2]
When I run:
Python demo.py
it traceback:

- jaypan@jaypan-X555LF:~/projects/SeqSLAM/pySeqSLAM/pyseqslam$ python demo.py 
Warning: Environment variable DATASET_1_PATH not found! Trying '../datasets/nordland/64x32-grayscale-1fps/spring'
Warning: Environment variable DATASET_2_PATH not found! Trying '../datasets/nordland/64x32-grayscale-1fps/winter'
Preprocessing dataset spring, indices 1 - 35601 ...
/home/jaypan/projects/SeqSLAM/pySeqSLAM/pyseqslam/seqslam.py:139: RuntimeWarning: invalid value encountered in divide
  img[n[i]:n[i+1], m[j]:m[j+1]] = 127+np.reshape(np.round((pp-np.mean(pp))/np.std(pp, ddof=1)), (s, s))
Traceback (most recent call last):
  File "demo.py", line 99, in <module>
    demo()
  File "demo.py", line 82, in demo
    results = ss.run()
  File "/home/jaypan/projects/SeqSLAM/pySeqSLAM/pyseqslam/seqslam.py", line 22, in run
    results = self.doPreprocessing()
  File "/home/jaypan/projects/SeqSLAM/pySeqSLAM/pyseqslam/seqslam.py", line 60, in doPreprocessing
    savemat(filename, {'results_preprocessing': results_preprocessing})
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 204, in savemat
    file_stream = open(file_name, 'wb')
IOError: [Errno 2] No such file or directory: 'results/preprocessing-spring-1-100-35601.mat'
What's the wrong?

**Comment by Eric-BB** [comment]
Hello tmadl and Jaypancool:

        I get the same error, could you tell me where I can download the file results/preprocessing-spring-1-100-35601.mat?

**Comment by Eric-BB** [comment]
Hello tmadl and Jaypancool:

    I get the same error, could you tell me where I can download the file results/preprocessing-spring-1-100-35601.mat? @tmadl  @Jaypancool

**Comment by marsywhuang** [comment]
Hi Jaypancool
Try to give a subdirectory, which name is results, under pyseqslam directory

**Comment by Ahmedest61** [comment]
I'm facing following error when I run the demo.py script
"""
    v = D[a:b, :]
TypeError: slice indices must be integers or None or have an __index__ method
"""
Is any of you came across this error?

**Comment by hmishra2250** [comment]
The solution is to create a **results** directory inside the **pyseqslam** directory and then run demo. It will automatically take care of the rest.

**Comment by LYRen1900** [comment]
> I'm facing following error when I run the demo.py script
> """
> v = D[a:b, :]
> TypeError: slice indices must be integers or None or have an **index** method
> """
> Is any of you came across this error?

Hi, Ahmedest61.
line 189 and 190 in pyseqslam.py , it is should be changed as: "a=np.max((0, i-self.params.contrastEnhancement.R//2))
            b=np.min((D.shape[0], i+self.params.contrastEnhancement.R//2+1)) "
line246 in pyseqslam.py , it is should be changed as :"for N in range(self.params.matching.ds//2, DD.shape[1]-self.params.matching.ds//2): "
